# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ztranslator(object):
    def setupUi(self, Ztranslator):
        Ztranslator.setObjectName("Ztranslator")
        Ztranslator.resize(1000, 570)
        font = QtGui.QFont()
        font.setItalic(True)
        Ztranslator.setFont(font)
        Ztranslator.setStyleSheet("QTextEdit {\n"
"    background-color: white;\n"
"    padding: 15px 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    \n"
"    background-color: rgb(0, 136, 255);\n"
"    color: rgb(255, 192, 3);\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgb(0, 136, 180);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Ztranslator)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 741, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 130, 441, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.textEdit.setFont(font)
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(530, 130, 441, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(530, 90, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Light")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(270, 90, 201, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(760, 90, 201, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 400, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 400, 101, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(880, 400, 91, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(30, 450, 321, 21))
        self.checkBox.setObjectName("checkBox")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(30, 490, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        Ztranslator.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(Ztranslator)
        self.statusBar.setObjectName("statusBar")
        Ztranslator.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(Ztranslator)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        Ztranslator.setMenuBar(self.menuBar)
        self.actionSave = QtWidgets.QAction(Ztranslator)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.actionSave.setFont(font)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(Ztranslator)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionCopy = QtWidgets.QAction(Ztranslator)
        self.actionCopy.setObjectName("actionCopy")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menuEdit.addAction(self.actionCopy)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(Ztranslator)
        QtCore.QMetaObject.connectSlotsByName(Ztranslator)

    def retranslateUi(self, Ztranslator):
        _translate = QtCore.QCoreApplication.translate
        Ztranslator.setWindowTitle(_translate("Ztranslator", "Ztranslator"))
        self.label.setText(_translate("Ztranslator", "Python Google Translator Made By Zubayer Rahaman"))
        self.textEdit.setHtml(_translate("Ztranslator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit.setPlaceholderText(_translate("Ztranslator", "Enter the Text You Wanna Translate"))
        self.textEdit_2.setPlaceholderText(_translate("Ztranslator", "Translated Text Will Appear Here"))
        self.label_2.setText(_translate("Ztranslator", "Select Language"))
        self.label_3.setText(_translate("Ztranslator", "Select Language"))
        self.pushButton.setToolTip(_translate("Ztranslator", "<html><head/><body><p>Translate the text</p></body></html>"))
        self.pushButton.setText(_translate("Ztranslator", "Translate"))
        self.pushButton_2.setToolTip(_translate("Ztranslator", "<html><head/><body><p>Clear all text</p></body></html>"))
        self.pushButton_2.setText(_translate("Ztranslator", "Clear"))
        self.pushButton_3.setToolTip(_translate("Ztranslator", "<html><head/><body><p>Copy translated text to clipboard</p></body></html>"))
        self.pushButton_3.setText(_translate("Ztranslator", "Copy"))
        self.checkBox.setText(_translate("Ztranslator", "Auto Detect Language"))
        self.menuFile.setTitle(_translate("Ztranslator", "File"))
        self.menuEdit.setTitle(_translate("Ztranslator", "Edit"))
        self.actionSave.setText(_translate("Ztranslator", "Save"))
        self.actionSave.setStatusTip(_translate("Ztranslator", "Save the translation to a text file"))
        self.actionSave.setShortcut(_translate("Ztranslator", "Ctrl+S"))
        self.actionOpen.setText(_translate("Ztranslator", "Open"))
        self.actionOpen.setStatusTip(_translate("Ztranslator", "Open and load text from a text file to be translated"))
        self.actionOpen.setShortcut(_translate("Ztranslator", "Ctrl+O"))
        self.actionCopy.setText(_translate("Ztranslator", "Copy"))
        self.actionCopy.setStatusTip(_translate("Ztranslator", "Copy the translated code"))
        self.actionCopy.setShortcut(_translate("Ztranslator", "Ctrl+C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ztranslator = QtWidgets.QMainWindow()
    ui = Ui_Ztranslator()
    ui.setupUi(Ztranslator)
    Ztranslator.show()
    sys.exit(app.exec_())
